### PR TITLE
Event toggle function pause

### PR DESCRIPTION
**Pull request by smbsp**
closes: #297 
Added an event ToggleFunctionPaused to the function toggleFunctionPause()
Shortened some error messages to downsize the contract `LoanTokenLogicStandard`

### CODE REVIEW

**Review by computerphysicslab — APPROVED** [review]
Good job!

**Review by tjcloa — APPROVED** [review]
lgtm

**Comment by smbsp** [comment]
This is on hold due to Contract Size issue and needs to be re-visited.

**Comment by smbsp** [comment]
The new PR is: https://github.com/DistributedCollective/Sovryn-smart-contracts/pull/357

This is built on updated Loan Token logic and hence resolves the Contract Size issue.

**Pull request closed without merging**
