### PR TITLE
Events for backend

### LINKED ISSUE #309: Add events to facilitate FE/BE data processing
https://docs.google.com/spreadsheets/d/1Gf6CS42qxveyy0B2cx38Y0NUycVjU3Nm7GYot0Blnd0/edit#gid=0
**Contacts:**
Betsy Braddock

### PR DESCRIPTION
**Pull request by computerphysicslab**
1 event renamed and added extra parameters
1 new event

More details on:
https://github.com/DistributedCollective/Sovryn-smart-contracts/issues/309

Fix #309

### CODE REVIEW

**Review by BetsyBraddock — COMMENTED** [review]
Thanks for these changes Juan, this looks good. Let me know when it's merged and I'll update the database

**Comment by computerphysicslab** [comment]
Checking redeployability:
Apart from Staking contract that is upgradable by SIP, these events are modifying Checkpoints.sol or InterestUser.sol, so I need to check out:
1.- What instances are inheriting Checkpoints.sol or InterestUser.sol?
2.- Are they redeployable?

**Comment by computerphysicslab** [comment]
> Checking redeployability:
> Apart from Staking contract that is upgradable by SIP, these events are modifying Checkpoints.sol or InterestUser.sol, so I need to check out:
> 1.- What instances are inheriting Checkpoints.sol or InterestUser.sol?
> 2.- Are they redeployable?

https://docs.google.com/document/d/1gGY4Rua_FVBZCJCftzf14cD4c6kqg6VTr9g-9-uDCA0/edit

List Upgradeable Smart Contracts (Sovryn)

LoanToken Contract
LoanTokenLogicStandard Contract
LoanTokenLogicDai Contract
LoanTokenLogicWrbtc Contract
LoanClosings Contract
LoanOpenings Contract
LoanMaintenance Contract
LoanSettings Contract
SwapsExternal Contract
PriceFeeds Contract
SwapsImplSovrynSwap Contract
ProtocolSettings Contract
Staking Contract
FeeSharingProxy Contract

Thenm how about Checkpoints.sol and InterestUser.sol ?

Checkpoints.sol is inherited by:
    WeightedStaking
        Staking

InterestUser.sol is inherited by:
    LoanClosingsBase
    LoanClosingsWith
    LoanMaintenance
    LoanOpenings

**So it seems to me like both contracts are effectively upgradable.**

**Comment by computerphysicslab** [comment]
Parameter amount has been added to ExtendedStakingDuration event.

**Review by tjcloa — APPROVED** [review]
Before merging to the development branch please make sure the redeployment script is ready

**Pull request merged**
